---
title: "Figure 2KLM"
author: "Yufeng"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(!is.element("crossRanger", installed.packages()[, 1])) devtools::install_github('shihuang047/crossRanger')
if(!is.element("phyloseq", installed.packages()[, 1])) BiocManager::install("phyloseq")
if(!is.element("clusterProfiler", installed.packages()[, 1])) BiocManager::install("clusterProfiler")

p <- c("ggplot2", "RColorBrewer", "viridis", "palmerpenguins", "tidyverse", "pheatmap", 
       "colorspace", "dplyr", "stats", "grDevices", "graphics", "reshape2", "corrplot", 
       "GGally", "ggimage", "pdftools", "ggpubr", "DistVis", "biomformat", "crossRanger", 
       "phyloseq", "clusterProfiler")
usePackage <- function(p) {
  if (!is.element(p, installed.packages()[,1])) {
    install.packages(p, dep=TRUE, repos="https://cloud.r-project.org/")
  }
  suppressWarnings(suppressMessages(invisible(require(p, character.only=TRUE))))
}
invisible(lapply(p, usePackage))

source("../Utilities/data_trimming_util.R")

outdir <- "../../Results/Figure_2"
if(! dir.exists(outdir)) {
  dir.create(outdir, recursive = T)
}
```

```{r}
Index<-function(mat,A=Increased,B=Decreased){
  #-------------------------------Data check
  if(!all(is.na(A))){
    Mis_A<-A[which(!A %in% colnames(mat))]
    if(length(Mis_A)>0){
      cat(length(Mis_A),' "Incresed" varible(s) NOT found in data: ',Mis_A,'\n',sep=' ')
      A<-A[which(!A %in% Mis_A)]}
  }
  if(!all(is.na(B))){
    Mis_B<-B[which(!B %in% colnames(mat))]
    if(length(Mis_B)>0){
      cat(length(Mis_B),' "Decresed" varible(s) NOT found in data: ',Mis_B,'\n',sep=' ')
      B<-B[which(!B %in% Mis_B)]}
  }
  
  cat(length(A),' "Incresed" varible(s) found and used for Index calculation: ',A,'\n',sep=' ')
  cat(length(B),' "Decresed" varible(s) found and used for Index calculation: ',B,'\n',sep=' ')
  log.mat<-function(mat,base=2){
    #mat[mat==0]<-0.000001
    mat[mat < 1e-6] <- 1e-6
    log.mat<-log(mat,base)
    return(log.mat)
  }
  log_mat<-log.mat(mat)
  #-------------------------------Index calculation
  if(!all(is.na(A)) & !all(is.na(B))){
    Index<-apply(log_mat,1,function(x){sum(x[A])/length(A)-sum(x[B])/length(B)})
  }else if(all(is.na(A)) & !all(is.na(B))){
    Index<-apply(log_mat,1,function(x){sum(x[B])/length(B)})
  }else{
    Index<-apply(log_mat,1,function(x){sum(x[A])/length(A)})
  }
  
  objectList   <- list()
  objectList$Index <- Index
  objectList$A <- A
  objectList$B <- B
  
  invisible(objectList)
}
```

```{r}
count_file_1867 <- "../../Data/1867/function/1867_functional_kos_count_table.biom"
metadata_file_1867 <- "../../Data/1867/1867_metadata.txt"
taxonomy_file_1867 <- "../../Data/1867/function/1867_functional_annotation.txt"

count_file_637 <- "../../Data/637/function/637_functional_kos_count_table.biom"
metadata_file_637 <- "../../Data/637/637_metadata.txt"
taxonomy_file_637 <- "../../Data/637/function/637_functional_annotation.txt"

mapping_file <- "../../Data/Figure_2/Mapping_of_tooth_position.txt"
```

```{r, message = FALSE}
count <- read_hdf5_biom(count_file_1867)
count <- biom(count)
count <- biom_data(count)
count <- as.matrix(t(count))
abd_1867 <- count / rowSums(count)

metadata_1867 <- read.table(metadata_file_1867, sep = "\t", header = T, row.names = 1)
identical(rownames(abd_1867), rownames(metadata_1867))

taxonomy_1867 <- read.table(taxonomy_file_1867, sep = "\t", header = T, row.names = 1, comment.char = "")

count <- read_hdf5_biom(count_file_637)
count <- biom(count)
count <- biom_data(count)
count <- as.matrix(t(count))
abd_637 <- count / rowSums(count)

metadata_637 <- read.table(metadata_file_637, sep = "\t", header = T, row.names = 1)
identical(rownames(abd_637), rownames(metadata_637))

taxonomy_637 <- read.table(taxonomy_file_637, sep = "\t", header = T, row.names = 1, comment.char = "")

mapping <- read.table(mapping_file, sep = "\t", header = T, row.names = 1)
```

```{r, echo = FALSE, print = FALSE}
H2H_metadata_1867 <- subset(metadata_1867, HostGroup == "H2H")
H2H_abd_1867 <- H2H_abd_1867[which(rownames(H2H_abd_1867) %in% rownames(H2H_metadata_1867)), 
                             which(colSums(H2H_abd_1867) != 0)]
identical(rownames(H2H_metadata_1867), rownames(H2H_abd_1867))

y <- factor(H2H_metadata_1867$NicheICM)
result_clr_1867 <- BetweenGroup.test(H2H_abd_1867, y, clr_transform=TRUE)

sig_result_clr_1867 <- subset(result_clr_1867, IfSig == "Sig")
```

```{r}
gene_list <- rownames(sig_result_clr_1867)
gene_list <- gsub("^K0+", "", gene_list)
gene_list <- gsub("^K", "", gene_list)
ko_richiness_results <- enrichKEGG(gene_list)
ko_richiness_results <- ko_richiness_results@result
ko_richiness_results <- mutate(ko_richiness_results, 
                               richFactor = Count / as.numeric(sub("/\\d+", "", BgRatio)))

kos_list <- list()

for (i in 1:nrow(ko_richiness_results)) {
  kos <- strsplit(ko_richiness_results$geneID[i], "/")[[1]]
  kos_list[[ko_richiness_results$Description[i]]] <- kos
}

kos_list <- stack(kos_list)

kos_list$values <- as.integer(kos_list$values)
kos_list$values <- sprintf("%05d", kos_list$values)
kos_list$values <- gsub("^", "K", kos_list$values)
```

Figure 2K
```{r}
H2H_metadata_637 <- subset(metadata_637, HostGroup == "H2H")
H2H_abd_637 <- subset(abd_637, rownames(abd_637) %in% rownames(H2H_metadata_637))
identical(rownames(H2H_metadata_637), rownames(H2H_abd_637))

H2H_sig_abd_637 <- H2H_abd_637[ , colnames(H2H_abd_637) %in% rownames(sig_result_clr_1867)]
H2H_sig_abd_637 <- t(H2H_sig_abd_637)

df <- merge(H2H_sig_abd_637, kos_list, by.x = 0, by.y = 1, all = F)

df <- df[, -1]
summarized_df <- df %>%
  group_by(ind) %>%
  summarize(across(everything(), sum))

df <- melt(summarized_df)
df <- merge(df, H2H_metadata_637, by.x = 2, by.y = 0, all = T)

summarized_df <- df %>%
  group_by(ind, Position2) %>%
  summarize(abd = mean(value))

ranked_data <- summarized_df %>%
  dplyr::group_by(ind) %>%
  dplyr::mutate(rank = rank(abd)) %>%
  dplyr::ungroup()

ordered_inds <- subset(ranked_data, Position2 == "T51")
ordered_inds$ind <- as.character(ordered_inds$ind)
ordered_inds <- ordered_inds %>% arrange(rank, ind)
ordered_inds <- ordered_inds$ind

ranked_data$ind <- factor(ranked_data$ind,
                          levels = ordered_inds,
                          ordered = T)
ranked_data$Position2 <- factor(ranked_data$Position2, 
                                levels = c("T55", "T54", "T53", "T52", "T51",
                                           "T61", "T62", "T63", "T64", "T65", 
                                           "T75", "T74", "T73", "T72", "T71",
                                           "T81", "T82", "T83", "T84", "T85"),
                                ordered = T)

plot1 <- ggplot(ranked_data, aes(Position2, ind, fill = rank)) +
  geom_tile() +
  scale_fill_viridis()+
  xlab("Tooth position") + 
  ylab("Enriched pathway") + 
  theme_bw() + 
  theme(strip.text = element_text(size = 15),
        legend.title = element_text(size = 15), 
        legend.text = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1),
        axis.text.y = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom")

plot1

ggsave(filename=paste0(outdir, "/Figure2_K_637_L3_enriched_spatial_sig_diff_ko_abd.pdf"), plot=plot1, width=15, height=50, limitsize = FALSE)
```


Figure 2L
```{r}
H2H_sig_abd_1867 <- H2H_abd_1867[ , colnames(H2H_abd_1867) %in% rownames(sig_result_clr_1867)]
H2H_sig_abd_1867 <- t(H2H_sig_abd_1867)
identical(colnames(H2H_sig_abd_1867), rownames(H2H_metadata_1867))

df <- merge(H2H_sig_abd_1867, kos_list, by.x = 0, by.y = 1, all = F)

df <- df[, -1]
summarized_df <- df %>%
  group_by(ind) %>%
  summarize(across(everything(), sum))

df <- melt(summarized_df)
df <- merge(df, H2H_metadata_1867, by.x = 2, by.y = 0, all = T)

summarized_df <- df %>%
  group_by(ind, Position2) %>%
  summarize(abd = mean(value))

ranked_data <- summarized_df %>%
  dplyr::group_by(ind) %>%
  dplyr::mutate(rank = rank(abd)) %>%
  dplyr::ungroup()

ranked_data <- dcast(ranked_data, ind ~ Position2)

other_positions <- unique(metadata_637[which(! metadata_637$Position2 %in% colnames(ranked_data)), "Position2"])
other_positions_table <- as.data.frame(matrix(NA, nrow = nrow(ranked_data), ncol = length(other_positions),
                                              dimnames = list(rownames(ranked_data), other_positions)))
ranked_data <- cbind(ranked_data, other_positions_table)
ranked_data$T51 <- ranked_data$T5161
ranked_data$T61 <- ranked_data$T5161
ranked_data <- ranked_data[, which(colnames(ranked_data) != "T5161")]

ranked_data <- melt(ranked_data, id.vars="ind")
colnames(ranked_data) <- c("ind", "Position2", "rank")

ranked_data$ind <- factor(ranked_data$ind,
                          levels = ordered_inds,
                          ordered = T)
ranked_data$Position2 <- factor(ranked_data$Position2, 
                                levels = c("T55", "T54", "T53", "T52", "T51",
                                           "T61", "T62", "T63", "T64", "T65", 
                                           "T75", "T74", "T73", "T72", "T71",
                                           "T81", "T82", "T83", "T84", "T85"),
                                ordered = T)

plot2 <- ggplot(ranked_data, aes(Position2, ind, fill = rank)) +
  geom_tile() +
  scale_fill_viridis()+
  xlab("Tooth position") + 
  ylab("Enriched pathway") + 
  theme_bw() + 
  theme(strip.text = element_text(size = 15),
        legend.title = element_text(size = 15), 
        legend.text = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1),
        axis.text.y = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom")

plot2
ggsave(filename=paste0(outdir, "/Figure2_L_1867_L3_enriched_spatial_sig_diff_ko_abd.pdf"), plot=plot2, width=15, height=50, limitsize = FALSE)
```

Figure 2M
```{r}
library(ggplot2)
library(forcats)
ko_richiness_results <- mutate(ko_richiness_results, 
        richFactor = as.numeric(sub("/\\d+", "", GeneRatio)) / as.numeric(sub("/\\d+", "", BgRatio)))

ko_richiness_results$Description <- 
  factor(ko_richiness_results$Description,
         levels = ordered_inds,
         ordered = T)
ko_richiness_results <- ko_richiness_results[order(ko_richiness_results$Description), ]
ko_richiness_results$order <- 1:nrow(ko_richiness_results)

plot3 <- ggplot(ko_richiness_results, showCategory = 32,
  aes(richFactor, fct_reorder(Description, order))) +
  #aes(richFactor, fct_reorder(Description, richFactor))) +
  geom_segment(aes(xend=0, yend = Description)) +
  geom_point(aes(color=p.adjust, size = Count)) +
  scale_color_gradientn(colours=c("#f7ca64", "#46bac2", "#7e62a3"),
                        trans = "log10",
                        guide=guide_colorbar(reverse=TRUE, order=1)) +
  scale_size_continuous(range=c(2, 10)) +
  xlab("Rich Factor") +
  ylab("Enriched pathway") +
  theme_bw() + 
  theme(strip.text = element_text(size = 15),
        legend.title = element_text(size = 15), 
        legend.text = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1),
        axis.text.y = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom")

plot3
ggsave(filename=paste0(outdir, "/Figure2_M_L3_enriched_spatial_sig_diff_ko_abd.pdf"), plot=plot2, width=15, height=50, limitsize = FALSE)
```


