---
title: "Figure 2IJ"
author: "Yufeng"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(!is.element("crossRanger", installed.packages()[, 1])) devtools::install_github('shihuang047/crossRanger')
if(!is.element("phyloseq", installed.packages()[, 1])) BiocManager::install("phyloseq")

p <- c("ggplot2", "RColorBrewer", "viridis", "palmerpenguins", "tidyverse", "pheatmap", 
       "colorspace", "dplyr", "stats", "grDevices", "graphics", "reshape2", "corrplot", 
       "GGally", "ggimage", "pdftools", "ggpubr", "DistVis", "biomformat", "crossRanger", 
       "phyloseq")
usePackage <- function(p) {
  if (!is.element(p, installed.packages()[,1])) {
    install.packages(p, dep=TRUE, repos="https://cloud.r-project.org/")
  }
  suppressWarnings(suppressMessages(invisible(require(p, character.only=TRUE))))
}
invisible(lapply(p, usePackage))

source("../Utilities/data_trimming_util.R")

outdir <- "../../Results/Figure_2"
if(! dir.exists(outdir)) {
  dir.create(outdir, recursive = T)
}
```

```{r}
Index<-function(mat,A=Increased,B=Decreased){
  #-------------------------------Data check
  if(!all(is.na(A))){
    Mis_A<-A[which(!A %in% colnames(mat))]
    if(length(Mis_A)>0){
      cat(length(Mis_A),' "Incresed" varible(s) NOT found in data: ',Mis_A,'\n',sep=' ')
      A<-A[which(!A %in% Mis_A)]}
  }
  if(!all(is.na(B))){
    Mis_B<-B[which(!B %in% colnames(mat))]
    if(length(Mis_B)>0){
      cat(length(Mis_B),' "Decresed" varible(s) NOT found in data: ',Mis_B,'\n',sep=' ')
      B<-B[which(!B %in% Mis_B)]}
  }
  
  cat(length(A),' "Incresed" varible(s) found and used for Index calculation: ',A,'\n',sep=' ')
  cat(length(B),' "Decresed" varible(s) found and used for Index calculation: ',B,'\n',sep=' ')
  log.mat<-function(mat,base=2){
    #mat[mat==0]<-0.000001
    mat[mat < 1e-6] <- 1e-6
    log.mat<-log(mat,base)
    return(log.mat)
  }
  log_mat<-log.mat(mat)
  #-------------------------------Index calculation
  if(!all(is.na(A)) & !all(is.na(B))){
    Index<-apply(log_mat,1,function(x){sum(x[A])/length(A)-sum(x[B])/length(B)})
  }else if(all(is.na(A)) & !all(is.na(B))){
    Index<-apply(log_mat,1,function(x){sum(x[B])/length(B)})
  }else{
    Index<-apply(log_mat,1,function(x){sum(x[A])/length(A)})
  }
  
  objectList   <- list()
  objectList$Index <- Index
  objectList$A <- A
  objectList$B <- B
  
  invisible(objectList)
}
```

```{r}
count_file_1867 <- "../../Data/1867/taxonomy/1867_taxonomic_ASV_count_table.biom"
metadata_file_1867 <- "../../Data/1867/1867_metadata.txt"
taxonomy_file_1867 <- "../../Data/1867/taxonomy/1867_taxonomic_feature_taxon_SILVA.txt"

count_file_637 <- "../../Data/637/taxonomy/637_taxonomic_ASV_count_table.biom"
metadata_file_637 <- "../../Data/637/637_metadata.txt"
taxonomy_file_637 <- "../../Data/637/taxonomy/637_taxonomic_feature_taxonomy.txt"

mapping_file <- "../../Data/Figure_2/Mapping_of_tooth_position.txt"
```

```{r, message = FALSE}
count <- read_hdf5_biom(count_file_1867)
count <- biom(count)
count <- biom_data(count)
count <- as.matrix(t(count))
abd_1867 <- count / rowSums(count)

metadata_1867 <- read.table(metadata_file_1867, sep = "\t", header = T, row.names = 1)
identical(rownames(abd_1867), rownames(metadata_1867))

taxonomy_1867 <- read.table(taxonomy_file_1867, sep = "\t", header = T, row.names = 1, comment.char = "")

count <- read_hdf5_biom(count_file_637)
count <- biom(count)
count <- biom_data(count)
count <- as.matrix(t(count))
abd_637 <- count / rowSums(count)

metadata_637 <- read.table(metadata_file_637, sep = "\t", header = T, row.names = 1)
identical(rownames(abd_637), rownames(metadata_637))

taxonomy_637 <- read.table(taxonomy_file_637, sep = "\t", header = T, row.names = 1, comment.char = "")

mapping <- read.table(mapping_file, sep = "\t", header = T, row.names = 1)
```

```{r, echo = FALSE, print = FALSE}
H2H_metadata_1867 <- subset(metadata_1867, HostGroup == "H2H")
H2H_abd_1867 <- subset(abd_1867, rownames(abd_1867) %in% rownames(H2H_metadata_1867))
identical(rownames(H2H_metadata_1867), rownames(H2H_abd_1867))

y <- factor(H2H_metadata_1867$NicheICM)
result_clr_1867 <- BetweenGroup.test(H2H_abd_1867, y, clr_transform=TRUE)

sig_result_clr_1867 <- subset(result_clr_1867, IfSig == "Sig")
```
Figure 2I
```{r}
H2H_metadata_637 <- subset(metadata_637, HostGroup == "H2H")
H2H_abd_637 <- subset(abd_637, rownames(abd_637) %in% rownames(H2H_metadata_637))
identical(rownames(H2H_metadata_637), rownames(H2H_abd_637))

H2H_sig_abd_637 <- H2H_abd_637[ , colnames(abd_637) %in% rownames(sig_result_clr_1867)]
matched_index <- match(colnames(H2H_sig_abd_637), rownames(taxonomy_637))
colnames(H2H_sig_abd_637) <- taxonomy_637[matched_index, "Brief_Taxon_ASV"]

H2H_sig_abd_637 <- as.matrix(H2H_sig_abd_637)
df_637 <- melt(H2H_sig_abd_637)
df_637 <- merge(df_637, metadata_637, by.x = 1, by.y = 0, all.x = T, all.y = F)
df_637 <- df_637 %>%
  group_by(Var2, Position2) %>%
  summarise(mean_abd = mean(value))

ranked_df_637 <- df_637 %>%
  group_by(Var2) %>%
  mutate(rank = rank(mean_abd)) %>%
  ungroup()

ordered_features <- subset(ranked_df_637, Position2 == "T51")
ordered_features$feature <- as.character(ordered_features$Var2)
ordered_features <- ordered_features %>% arrange(rank, Var2)
ordered_features <- ordered_features$feature

ranked_df_637$Var2 <- factor(ranked_df_637$Var2, levels = ordered_features, ordered = T)
matched_index <- match(ranked_df_637$Position2, mapping$Position2)
ranked_df_637$Tooth_num <- mapping[matched_index, "Position0"]
ranked_df_637 <- ranked_df_637[order(ranked_df_637$Tooth_num), ]
ranked_df_637$Position2 <- factor(ranked_df_637$Position2, levels = unique(ranked_df_637$Position2), ordered = T)

plot <- ggplot(ranked_df_637, aes(Position2, Var2, fill = rank)) +
  geom_tile() +
  scale_fill_viridis()+
  xlab("Tooth position") + 
  ylab("ASV") + 
  theme_bw() + 
  theme(strip.text = element_text(size = 14),
        legend.title = element_text(size = 14), 
        legend.text = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1),
        axis.text.y = element_text(size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank())

plot

ggsave(filename=paste0(outdir, "/Figure2_I_637_spatial_sig_diff_asv_abd.pdf"), plot=plot, width=10, height=3.5)
```


Figure 2J
```{r}
H2H_sig_abd_1867 <- H2H_abd_1867[ , colnames(abd_1867) %in% rownames(sig_result_clr_1867)]
matched_index <- match(colnames(H2H_sig_abd_1867), rownames(taxonomy_1867))
colnames(H2H_sig_abd_1867) <- taxonomy_1867[matched_index, "Brief_Taxon_ASV"]

H2H_sig_abd_1867 <- as.matrix(H2H_sig_abd_1867)
df_1867 <- melt(H2H_sig_abd_1867)
df_1867 <- merge(df_1867, metadata_1867, by.x = 1, by.y = 0, all.x = T, all.y = F)
df_1867 <- df_1867 %>%
  group_by(Var2, Position2) %>%
  summarise(mean_abd = mean(value))

ranked_df_1867 <- df_1867 %>%
  group_by(Var2) %>%
  mutate(rank = rank(mean_abd)) %>%
  ungroup()

df_1867 <- ranked_df_1867[, c("Position2", "Var2", "rank")]
df_1867 <- dcast(df_1867, Var2 ~ Position2)

other_positions <- mapping[which(! mapping$Position2 %in% colnames(df_1867)), "Position2"]
other_positions_table <- as.data.frame(matrix(NA, nrow = nrow(df_1867), ncol = length(other_positions),
                                              dimnames = list(rownames(df_1867), other_positions)))
df_1867 <- cbind(df_1867, other_positions_table)

df_1867$T51 <- df_1867$T5161
df_1867$T61 <- df_1867$T5161
df_1867 <- df_1867[, which(colnames(df_1867) != "T5161")]

df_1867 <- melt(df_1867, id.vars="Var2")
colnames(df_1867) <- c("feature", "Position", "Rank")

df_1867$feature <- as.character(df_1867$feature)
df_1867$feature <- factor(df_1867$feature, levels = ordered_features, ordered = T)
matched_index <- match(df_1867$Position, mapping$Position2)
df_1867$Tooth_num <- mapping[matched_index, "Position0"]
df_1867 <- df_1867[order(df_1867$Tooth_num), ]
df_1867$Position <- factor(df_1867$Position, levels = unique(df_1867$Position), ordered = T)

plot <- ggplot(df_1867, aes(Position, feature, fill = Rank)) +
  geom_tile() +
  scale_fill_viridis()+
  xlab("Tooth position") + 
  ylab("ASV") + 
  theme_bw() + 
  theme(strip.text = element_text(size = 14),
        legend.title = element_text(size = 14), 
        legend.text = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1),
        axis.text.y = element_text(size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank())

plot

ggsave(filename=paste0(outdir, "/Figure2_J_1867_spatial_sig_diff_asv_abd.pdf"), plot=plot, width=10, height=3.5)
```


