---
title: "Figure 2BD"
author: "Yufeng"
output:
  pdf_document: default
---

# Spatial Gradient of PC1 in Cohort B

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

p <- c("reshape2","ggplot2", "dplyr", "viridis", "colorspace", "RColorBrewer", "cowplot", "grid", "gridExtra", "gtable",
       "ggpubr", "patchwork", "vegan", "plyr")
usePackage <- function(p) {
  if (!is.element(p, installed.packages()[,1]))
    install.packages(p, dep=TRUE, repos="https://cloud.r-project.org/")
  suppressWarnings(suppressMessages(invisible(require(p, character.only=TRUE))))
}
invisible(lapply(p, usePackage))

source("../Utilities/data_trimming_util.R")

outdir <- "../../Results/Figure_2/"
if(! dir.exists(outdir)) {
  dir.create(outdir, recursive = T)
}
```

```{r}
metadata_file <- "../../Data/1867/1867_metadata.txt" 
taxonomic_pc_file <- "../../Results/Dist_matrix/1867_taxonomic_phylo_rPCA/1867_taxonomic_phylo_rpca_sample_coordinates.tsv"
functional_pc_file <- "../../Results/Dist_matrix/1867_functional_rPCA/1867_functional_rpca_sample_coordinates.tsv"

metadata <- read.table(metadata_file, header=T, sep="\t", row.names=1, quote="", comment.char="")
```

```{r}
pc1_position_group_boxplot <- function(df, metadata, mapping = data.frame()) {
  df<-df[order(rownames(df)), ]
  metadata<-metadata[order(rownames(metadata)),]
  identical(rownames(df), rownames(metadata))
  
  df <- merge(metadata[, c("Tooth_num2", "Position2", "NicheICM", "GroupHost2", "UL")], df, by="row.names", all=FALSE)
  
  if("T5161" %in% df$Position2) {
    x <- subset(df, Position2 == "T5161")
    x$Position2 <- "T51"
    df <- rbind(df, x)
    x$Position2 <- "T61"
    df <- rbind(df, x)
    df <- subset(df, Position2 != "T5161")
  }

  df <- rbind.fill(df, mapping)
  df <- df[order(df$Tooth_num2), ]
  df$Position2 <- factor(df$Position2, levels=unique(df$Position2), order = T)
  df$GroupHost2 <- factor(df$GroupHost2, levels=c("H2H", "H2H / C2C"), ordered = T)
  
  plot <- ggplot(df, aes(x = Position2, y = PC1)) +
    geom_boxplot(outlier.shape = NA) +
    scale_colour_manual(values = brewer.pal(8, "Pastel2")) +
    geom_jitter(aes(color=NicheICM), shape = 1, width = 0.2) +
    geom_smooth(mapping = aes(x = Position2, y = PC1, group = 1), data = subset(df, GroupHost2 == "H2H" & UL == "Upper_teeth"), method = "loess", se=TRUE) + 
    facet_wrap(~GroupHost2, scales = "free_x") +
    xlab("Tooth Position") + 
    ylab("PC1") + 
    theme_bw() + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          strip.text = element_text(size = 14),
          legend.title = element_text(size = 14), 
          legend.text = element_text(size = 14),
          axis.title.x = element_text(size = 14),
          axis.title.y = element_text(size = 14),
          axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1),
          axis.text.y = element_text(size = 14),
          legend.position = "bottom")
  return(plot)
}
```

```{r}
metadata_637 <- read.table("../../Data/637/637_metadata.txt", sep = "\t", header = T, row.names = 1)
mapping <- unique(metadata_637[, c("Tooth_num2", "Position2", "NicheICM", "UL")])
mapping$GroupHost2 <- "H2H"
x <- mapping
x$GroupHost2 <- "H2C / C2C"
mapping <- rbind(mapping, x)
x <- mapping
x$GroupHost2 <- "H2C / C2C"
mapping <- rbind(mapping, x)
```

Figure 2B
```{r, echo = FALSE, message=FALSE, warning=FALSE}
pcs <- read.table(taxonomic_pc_file, sep = "\t", header = T, row.names = 1)
identical(rownames(pcs), rownames(metadata))

plot <- pc1_position_group_boxplot(pcs, metadata, mapping)
plot
ggsave(filename=paste(outdir, "/Figure_2B_1867_taxonomic_phylo_rpca_PC1.pdf", sep=""), plot=plot, width=10, height=3.5)
```

Figure 2D
```{r, echo = FALSE, message=FALSE, warning = FALSE}
pcs <- read.table(functional_pc_file, sep = "\t", header = T, row.names = 1)
identical(rownames(pcs), rownames(metadata))

plot <- pc1_position_group_boxplot(pcs, metadata, mapping)
plot
ggsave(filename=paste(outdir, "/Figure_2D_1867_functional_rpca_PC1.pdf", sep=""), plot=plot, width=10, height=3.5)
```